@startuml

interface Product
interface Factory

class ConcreteProduct
class ConcreteProductFactory

'-------------------
Product <|.. ConcreteProduct
Factory <|.. ConcreteProductFactory
ConcreteProductFactory .> ConcreteProduct

@enduml